---
# yamllint disable rule:line-length
name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pgrubic_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Self test action
        id: action
        uses: ./
        with:
          pgrubic-version: "0.5.3"
          args: "format --check --diff"
      - name: Output installed pgrubic version
        run: echo ${{ steps.action.outputs.installed-pgrubic-version }}
