---
# yamllint disable rule:line-length
name: CI

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pgrubic_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Self test action
        id: action
        uses: ./
        with:
          pgrubic-version: 0.5.0

      - run: echo Installed pgrubic ${{ steps.action.outputspgrubic-version }}
        shell: bash
        # env:
        #   RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
